first_app/urls.py
from django.conf.urls import url
from first_app import views
app_name="first_app"

urlpatterns = [

    url(r'^aboutme/',views.about_me,name="aboutme"),
    url(r'^catagory/',views.catagory,name="catagory"),
    url(r'^seedetails/',views.details,name="details"),
    url(r'^get_comments/',views.get_comments,name="get_comments"),

    
]

my_blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from first_app import views
from django.conf.urls import include
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^first_app/',include("first_app.urls")),
]

first_app/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Catagory(models.Model):
    Name=models.CharField(max_length=40)
    def __str__(self):
        return self.Name

class Post(models.Model):
    PostId=models.AutoField(primary_key=True)
    Title=models.CharField(max_length=100)
    Body=models.CharField(max_length=1000000)
    Catagory=models.ForeignKey(Catagory)
    
    def __str__(self):
        return str(self.PostId)

class Comment(models.Model):
    ComId=models.AutoField(primary_key=True)
    Message=models.CharField(max_length=500)
    Email=models.EmailField(max_length=100)
    PostId=models.CharField(max_length=10000)

    def __str__(self):
        return str(self.ComId)

first_app/views.py
from django.shortcuts import render
from first_app.models import Catagory,Post,Comment
from django.http import HttpResponseRedirect
from django import forms
# Create your views here.


def index(request):
     catagory_list=Catagory.objects.all().order_by("Name")
     get_data=Post.objects.all().order_by("-PostId")
     my_list={"catagory":catagory_list,"all_data":get_data}     
     return render(request,"first_app/index.html",my_list)

def about_me(request):
    catagory_list=Catagory.objects.all().order_by("Name")
    my_list={"catagory":catagory_list}
    return render(request,"first_app/aboutme.html",my_list)

def catagory(request):
    catagory_list=Catagory.objects.all().order_by("Name") 
    get_catagory=request.GET["cat"]
    new_cat=Catagory.objects.get(Name=get_catagory)
    ##print(new_cat.id)
    get_data=Post.objects.all().filter(Catagory=new_cat.id).order_by("-PostId")
    my_list={"catagory":catagory_list,"data":get_data,"current_catagory":get_catagory}
    return render(request,"first_app/catagory.html",my_list)


def details(request):
     catagory_list=Catagory.objects.all().order_by("Name")
     get_id=request.GET["id"]
     get_data=Post.objects.get(PostId=get_id)
     get_comments=Comment.objects.all().filter(PostId=get_id).order_by("-ComId")
     ##print(get_data.Title)
     my_list={"catagory":catagory_list,"Post_data":get_data,"all_comments":get_comments}
     return render(request,"first_app/seedetails.html",my_list)

def get_comments(request):
     catagory_list=Catagory.objects.all().order_by("Name")
     if request.method=="POST":
          email=request.POST["email"]
          comments=request.POST["message"]
          email=email.lstrip()
          comments=comments.lstrip()
          ##print("ASCHIIIII!!!!")
          if(email!="" and comments!=""):
               new_Comments=Comment()
               new_Comments.Message=comments
               new_Comments.Email=email
               new_Comments.PostId=request.GET["id"]
               new_Comments.save()
     next = request.POST.get('next', '/')
     next+="?id="
     next+=request.GET["id"]
     return HttpResponseRedirect(next)
     ##return details(request)
          

templates/first_app/aboutme.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title_block %}
    <title>About Me</title>
    {% endblock %}
</head>
<body>
    {% block body_block %}
        <div class="jumbotron">
            <p>
                Actually This Website is made for practicing Python And Django
            </p>
            <h3>Developer Name: Md.Sifat Hassan</h3>
            <h3>University: American International University Bangladesh</h3>
            <div class="text-center">
            <figure class="figure">
                    <img src="{% static 'images/my_pic3.jpg' %}" class="figure-img img-fluid rounded" alt="My Picture" width="450px" height="400px">
                    <figcaption class="figure-caption"><b>Here is the developer enjoying his vacation</</figcaption>
            </figure>
            <br>
            <a href="https://www.linkedin.com/in/sifat-hassan-020004153/"><img src="{% static 'images/linkedin.png' %} " alt="Linkedin Profile" height="50px" weidth="60pc"></a>
            </div>
        </div>
    {% endblock %}
    
</body>
</html>

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {%block title_block %}
  <title>Document</title>
  {% endblock %}
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body style="font-family:'Montserrat', sans-serif;">
    <nav class="navbar sticky-top navbar-expand-md navbar-dark" style="background-color:rgb(66, 140, 244);margin-bottom:50px">
      <div style="color:white">
      <ul class="navbar-nav">
        <li>
          <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Catagory
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             {% for cat in catagory %}
              <a class="dropdown-item" href="{% url 'first_app:catagory' %}?cat={{cat.Name}}">{{cat.Name}}</a>
             {% endfor %}
            </div>
          </li>
        <li class="nav-item mr-sm-2">
          <a class="nav-link" href="{% url 'first_app:aboutme' %}" >About Me!</a>
        </li>
      </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
</body>
</html>

templates/first_app/catagory.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title_block %}
    <title>Catagory</title>
    {% endblock %}
</head>
<body>
    <div class="container" align="center">
        {% block body_block %}
            <h1>{{current_catagory}}</h1>
            <div class="container">
            {% if data %}
                {% for Data in data %}
                <div class="jumbotron" style="font-size: 16px" >
                    <h3 class="display-4" style="font-size: 26px"><b>{{Data.Title}}</b></h3>
                    <a href="{% url 'first_app:details'%}?id={{Data.PostId}}">See More</a>
                </div>
                {% endfor %}
            {% else %}
                <p>No POSTS YET</p>
            {% endif %}
            </div>

        {% endblock %}
    </div>
    
</body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title_block %}
    <title>Home</title>
    {% endblock %}
</head>
<body>
    {%block body_block %}
    <h1>Welcome To Sifat's Blog</h1>
    {% autoescape off %}
    {% for data in all_data %}
    <div class="jumbotron">
       
        <h3 class="display-3" style="font-size: 24px;color:blue"><b>{{data.Title|title}}</b></h3>
        <h4 class="display-4" style="font-size:16px;color:cornflowerblue">Catagory:{{data.Catagory}}</h4><br>
        <p class="card-text">{{ data.Body|slice:":100" }}....
            <a href="{% url 'first_app:details'%}?id={{data.PostId}}">See More</a>
        </p>
    </div>
    {% endfor %}
    {% endautoescape %}
    {% endblock %}
</body>
</html>

templates/first_app/seedetails.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'first_app/base.html' %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title_block %}
    <title>Document</title>
    {% endblock %}
</head>
<body>
    {%block body_block%}
    <div class="card" style="padding:10px">
        <h1 class="card-title"  style="font-size: 40px">{{Post_data.Title}}</h1>
        <h4 class="display-4" style="font-size: 20px">Catagory: {{Post_data.Catagory}}</h4>
        <hr>
        <div class="card-body">
        <p style="margin-top:50px" class="card-text">
        {% autoescape off %}
            {{Post_data.Body}}
        {% endautoescape %}
        </p>
         </div>
    </div>

    <div class="jumbotron" style="margin-top:10px">
        <h3 class="display-3" style="font-size:20px">Comments</h3>
        <form action="{% url 'first_app:get_comments' %}?id={{Post_data.PostId}}" method="POST" onsubmit="my_function()">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1">Email address</label>
                <input type="email" class="form-control" placeholder="name@example.com" name="email" id="email">
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Your Comments</label>
                <textarea class="form-control" rows="3" name="message" id="textcomments"></textarea>
            </div>
              <input type="hidden" name="next" value="{{request.path}}">
              <input type="submit" value="Submit" name="submit" class="btn btn-primary">
        </form>
        <div class="jumbotron jumbotron-fluid">
            {% if all_comments %}
                {% for com in all_comments %}
                    <p><b>{{com.Email}}</b><br>
                        <span style="margin-left:10px">{{com.Message}}</span></p>
                {% endfor %}
            {% else %}
                <p style="color:red">*No Commnets Available</p>
            {% endif %}
        </div>
    </div>
    <script src="../../static/javascript/script.js"></script>
    {% endblock %}
    
</body>
</html>